name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        filename: ingress.zip
        directory: custom_components/ingress
    - name: Upload
      uses: ncipollo/release-action@main
      with:
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        artifacts: custom_components/ingress/ingress.zip
        token: ${{ secrets.GITHUB_TOKEN }}
