name: Validate

on:
  push:
    branches-ignore: ['*']
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
